In [20]:
import os
print(os.getcwd())

C:\Users\onyan\anaconda_projects

In [5]:
import pandas as pd
df = pd.read_csv('weather.csv')
df

     Unnamed: 0              time  temperature  snowfall  humidity
0             0  2025-12-13T00:00          5.0       0.0        93
1             1  2025-12-13T01:00          4.8       0.0        93
2             2  2025-12-13T02:00          5.1       0.0        91
3             3  2025-12-13T03:00          5.5       0.0        92
4             4  2025-12-13T04:00          5.3       0.0        93
..          ...               ...          ...       ...       ...
163         163  2025-12-19T19:00          6.8       0.0        80
164         164  2025-12-19T20:00          7.0       0.0        79
165         165  2025-12-19T21:00          7.0       0.0        78
166         166  2025-12-19T22:00          6.8       0.0        79
167         167  2025-12-19T23:00          6.5       0.0        81

[168 rows x 5 columns]

In [42]:
df[['time','temperature']][df['temperature']==df['temperature'].min()]

                 time  temperature
101  2025-12-17T05:00          0.2

In [51]:
df.reset_index()

     humidity  Unnamed: 0              time  temperature  snowfall
0          93           0  2025-12-13T00:00          5.0       0.0
1          93           1  2025-12-13T01:00          4.8       0.0
2          91           2  2025-12-13T02:00          5.1       0.0
3          92           3  2025-12-13T03:00          5.5       0.0
4          93           4  2025-12-13T04:00          5.3       0.0
..        ...         ...               ...          ...       ...
163        80         163  2025-12-19T19:00          6.8       0.0
164        79         164  2025-12-19T20:00          7.0       0.0
165        78         165  2025-12-19T21:00          7.0       0.0
166        79         166  2025-12-19T22:00          6.8       0.0
167        81         167  2025-12-19T23:00          6.5       0.0

[168 rows x 5 columns]

In [6]:
weatherdata = [('1/10/26',23,6,'rainy'),('2/10/26',25,8,'cloudy'),('3/10/26',24,6,'windy')]
df=pd.DataFrame(weatherdata, columns=['date','temp','windspeed','event'])
df

      date  temp  windspeed   event
0  1/10/26    23          6   rainy
1  2/10/26    25          8  cloudy
2  3/10/26    24          6   windy

In [3]:
import os
os.getcwd()

'C:\\Users\\onyan\\anaconda_projects\\pandas'

In [17]:
import pandas as pd
def top_up(cell):
    if int(cell) >94:
        return int(cell) +2
    return cell
df=pd.read_csv('weather.csv', converters={
    'humidity': top_up
})
df.head(6)

   Unnamed: 0              time  temperature  snowfall humidity
0           0  2025-12-13T00:00          5.0       0.0       93
1           1  2025-12-13T01:00          4.8       0.0       93
2           2  2025-12-13T02:00          5.1       0.0       91
3           3  2025-12-13T03:00          5.5       0.0       92
4           4  2025-12-13T04:00          5.3       0.0       93
5           5  2025-12-13T05:00          5.0       0.0       97

In [13]:
import pandas as pd
df=pd.read_csv('customers.csv')
new_df=df.head(20).groupby('Country')

for country, c in new_df:
    print(country)
    print(c)

   Index      Customer Id First Name Last Name                   Company  \
1      2  10dAcafEBbA5FcA   Kristina   Ferrell  Horn, Shepard and Watson

         City  Country       Phone 1             Phone 2  \
1  Aaronville  Andorra  932-062-1802  (209)172-7124x3651

                     Email Subscription Date                   Website
1  xreese@hall-donovan.com        2020-04-27  https://tyler-pugh.info/
    Index      Customer Id First Name Last Name    Company      City Country  \
15     16  2cfDE68A372cC7A      Larry    Newton  Downs PLC  Mannstad  Belize

          Phone 1               Phone 2              Email Subscription Date  \
15  (216)514-1412  001-449-365-5864x147  ypayne@gaines.biz        2020-08-09

                  Website
15  https://figueroa.com/
    Index      Customer Id First Name Last Name                  Company  \
16     17  14CBc0BDfbE6FEA      Danny    Archer  Castro, Haney and Hanna

            City       Country     Phone 1                 Phone 2  \
16  East Diamond  Cook Islands  8416559700  001-212-234-3412x91164

                 Email Subscription Date                   Website
16  nwu@brady-chen.com        2021-05-21  http://www.callahan.net/
    Index      Customer Id First Name  Last Name                    Company  \
14     15  86Df56BFCc0a7CA  Catherine  Blackwell  Mack, Garcia and Schaefer

         City             Country                Phone 1             Phone 2  \
14  Lake Seth  Dominican Republic  001-915-961-8896x5744  (310)185-3032x0974

                       Email Subscription Date                      Website
14  calhounalisha@hardin.net        2021-03-30  https://barker-bishop.info/
   Index      Customer Id First Name Last Name       Company        City  \
7      8  47C5cEE243c9A7b      Glenn   Wiggins  Glenn-Harvey  Ambershire

                       Country           Phone 1     Phone 2  \
7  Falkland Islands (Malvinas)  245-207-5608x563  8806867785

                    Email Subscription Date              Website
7  changkellie@howell.com        2021-04-02  http://carlson.com/
    Index      Customer Id First Name Last Name      Company          City  \
18     19  dB52fA7Bec665C1    Kristin  Valencia  Liu-Douglas  Martinezstad

                        Country            Phone 1     Phone 2  \
18  French Southern Territories  443-671-1725x7073  6244311825

                      Email Subscription Date                Website
18  andrewsanders@marks.com        2021-04-17  http://www.myers.com/
    Index      Customer Id First Name Last Name                    Company  \
11     12  e586A2D67bcdB48       Sara   Shaffer  Dudley, Coleman and Green

       City Country     Phone 1                 Phone 2  \
11  Orrland  Gambia  4229986278  001-028-824-7381x56737

                     Email Subscription Date                         Website
11  gabrielaleach@rose.net        2021-04-07  https://www.hoffman-rubio.com/
   Index      Customer Id First Name  Last Name       Company         City  \
4      5  5820deAdCF23EFe   Kathleen  Mccormick  Carson-Burch  Andresmouth

  Country                Phone 1           Phone 2  \
4   Macao  001-184-153-9683x1497  552.051.2979x342

                              Email Subscription Date              Website
4  alvaradojesse@rangel-shields.com        2021-01-17  https://welch.info/
    Index      Customer Id First Name Last Name    Company         City  \
10     11  9653ca648e2E414     Martin   Hawkins  Lopez Inc  Lake Bobton

       Country           Phone 1       Phone 2                        Email  \
10  Mauritania  001-402-567-1320  732-908-7945  danielbuckley@hatfield.info

   Subscription Date                  Website
10        2021-05-02  https://www.newman.com/
   Index      Customer Id First Name Last Name      Company         City  \
2      3  67DAB15Ebe4BE4a     Briana  Andersen  Irwin-Oneal  East Jordan

  Country     Phone 1        Phone 2                          Email  \
2   Nepal  8352752061  (567)135-1918  haleybraun@blevins-sexton.com

  Subscription Date                     Website
2        2022-03-22  https://www.mack-bell.net/
    Index      Customer Id First Name Last Name                  Company  \
13     14  f8dddbf9CD6FF92       Glen   Hammond  Schaefer, Chung and Lin

          City      Country               Phone 1                 Phone 2  \
13  Pamelatown  Netherlands  001-887-543-3745x055  001-955-888-1987x09071

                Email Subscription Date                  Website
13  lweeks@hooper.org        2022-03-03  https://bush-huynh.org/
   Index      Customer Id First Name Last Name           Company  \
3      4  6d350C5E5eDB4EE      Patty     Ponce  Richardson Group

               City                   Country       Phone 1           Phone 2  \
3  East Kristintown  Northern Mariana Islands  302.398.3833  196-189-7767x770

                  Email Subscription Date                        Website
3  hohailey@anthony.com        2020-07-02  https://delacruz-freeman.org/
   Index      Customer Id First Name Last Name       Company  \
0      1  EB54EF1154C3A78    Heather  Callahan  Mosley-David

               City Country       Phone 1       Phone 2  \
0  Lake Jeffborough  Norway  043-797-5229  915.112.1727

                          Email Subscription Date                  Website
0  urangel@espinoza-francis.net        2020-08-26  http://www.escobar.org/
    Index      Customer Id First Name Last Name       Company           City  \
17     18  48b3ACBfD6A5cdC        Kim   Griffin  Tyler-Levine  New Gwendolyn

                  Country            Phone 1            Phone 2  \
17  Saint Kitts and Nevis  597.367.9499x5429  506.141.4174x6326

                  Email Subscription Date                             Website
17  harold11@mullen.org        2021-06-02  http://www.mclaughlin-hubbard.net/
   Index      Customer Id First Name Last Name       Company  \
5      6  E1CDEaC63fDd5aA     Trevor       Lee  Maddox Group

                 City  Country               Phone 1          Phone 2  \
5  Lake Madelineburgh  Senegal  +1-134-348-0265x9132  +1-313-882-4167

                    Email Subscription Date                   Website
5  briangriffin@chang.org        2021-08-13  https://www.roberts.com/
    Index      Customer Id First Name Last Name      Company             City  \
19     20  e99DcfDaDac8a06     Hannah    Ramsey  Hicks-Duran  Port Adrianport

      Country              Phone 1            Phone 2             Email  \
19  Singapore  (822)795-8754x29384  (769)638-7026x967  amy99@booker.com

   Subscription Date                       Website
19        2020-12-30  http://www.larsen-floyd.biz/
    Index      Customer Id First Name Last Name          Company  \
12     13  c388ECa44FFe37c       Dave     Moran  Harrell-Donovan

               City Country            Phone 1       Phone 2  \
12  South Elizabeth  Sweden  575.006.7250x9748  262-029-1096

                      Email Subscription Date               Website
12  cartermallory@chung.com        2020-02-28  https://hinton.info/
   Index      Customer Id First Name Last Name                      Company  \
9     10  436b9c41cfb1fa3    Brendan    Franco  Schaefer, Blair and Shaffer

         City  Country           Phone 1            Phone 2  \
9  New Rickey  Ukraine  001-315-224-3556  254-621-7128x7573

                       Email Subscription Date           Website
9  kentryan@stone-oneill.com        2021-06-29  http://ruiz.com/
   Index      Customer Id First Name Last Name                   Company  \
6      7  3e1187fCcebC8d2     Mathew   Hoffman  Bender, Pittman and Kidd

         City     Country       Phone 1              Phone 2  \
6  West Ralph  Uzbekistan  842.380.1168  (178)178-5447x32603

                      Email Subscription Date               Website
6  bauergerald@morrison.com        2020-04-09  http://www.holt.com/
   Index      Customer Id First Name Last Name                  Company  \
8      9  cacaD68a5e4BF4b      Bruce     Payne  Arroyo, Cain and Hudson

          City   Country             Phone 1       Phone 2  \
8  Barrettview  Zimbabwe  391.313.4649x42910  166.227.5055

                          Email Subscription Date                      Website
8  mayerjerome@hurst-graham.net        2020-11-26  https://www.glenn-snow.com/